### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by valento92** [protyze/aframe-alongpath-component#3]
Greetings!

Would it be possible if you could make rotation to follow along the path? I am using your component with the camera and it is working perfectly, except that it won't change rotation based on the spline.

**Comment by valento92** [comment]
I toyed around and adding these lines where you set the position could work:

`var r = this.curve.getTangent(i);
//this.el.setAttribute('rotation', r);
this.el.components.camera.camera.lookAt(this.curve.getTangent( i ));`

**Comment by protyze** [comment]
Hi and sorry for the late fix…

Functionality is now added to the latest version!

**Comment by valento92** [comment]
Ahm, sorry I have to say: you're so badass! I couldn't ever come up with all that formula! Great job. :)

**Comment by aalavandhaann** [comment]
@protyze 
I guess the rotation is happening around all the axis to follow a path. Is it possible to specify the rotation axis when following a path? Imagine the animation of a truck following a path on the road. It constantly rotates around the y-axis to align to the path. As of now it will rotate around all axis, which is not correct.

Also another thing I noticed is that the speed or time taken to travel between two points is not dependent on the `distance_between_2points / curve_length`. The time taken by an object to move between two points is always constant. For example in a path that has points distributed at unequal intervals then this would be a nice way to show an uniform movement along the path. Sometimes in a path combining a curve and straight line this will be true. For the number of points along the curve will be dense, and when the path becomes more linear (straight) from a curve then we won't need more points to define a straight line. 

BTW, if someone wants to extract the curve from Blender to be used in A-Frame, use the below python script. Copy the html from the terminal and paste in your html

```
import bpy;
c = bpy.context;
curve = c.active_object;
spline = curve.data.splines[0];
print('<a-curve id="pathname">');
for i,p in enumerate(spline.points):
    x,y,z,w = p.co;
    print('<a-curve-point position="%f %f %f"></a-curve-point>'%(x,z,-y));
print('</a-curve>');
```

Regards,

#0K
